42_cursus/Transcendence/T1/django/ft_transcendence/chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'

urlpatterns = [
    path("", views.index, name="index"),
    path("<str:room_name>/<int:userID>", views.room, name="room"),
    path("<int:userID>/", views.get_room_redirect, name="get_room_redirect"),
    path("direct_message/", views.direct_message, name='direct_message')
]

42_cursus/Transcendence/T1/django/ft_transcendence/core/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'core'

urlpatterns = [
	path("", views.login, name="login"),
	path("mfa/", views.mfa, name="mfa"),
	path("logout/", views.logout, name="logout"),
	path("home/", views.home, name="home"),
	path("my_profile/", views.my_profile, name="my_profile"),
	path("profile/<str:username>", views.profile, name="profile"),
	path("social/", views.social, name="social"),
	path("send_friend_request/<int:userID>/", views.send_friend_request, name="send_friend_request"),
	path("accept_friend_request/<int:friendRequestID>/", views.accept_friend_request, name="accept_friend_request"),
	path("decline_friend_request/<int:friendRequestID>/", views.decline_friend_request, name="decline_friend_request"),
	path("cancel_friend_request/<int:userID>/", views.cancel_friend_request, name="cancel_friend_request"),
	path("remove_friend/<int:friendID>/", views.remove_friend, name="remove_friend"),
	path("block_user/<int:userID>/", views.block_user, name="block_user"),
	path("notifications/", views.notifications, name="notifications"),
	path("unblock_user/<int:userID>/", views.unblock_user, name="unblock_user")

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

42_cursus/Transcendence/T1/django/ft_transcendence/ft_transcendence/urls.py
from django.contrib import admin
from django.urls import include, path
from core import views
from django.contrib.auth.models import User
from rest_framework import routers
from api import views
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

# Routers provide an easy way of automatically determining the URL conf.
# Because we use ViewSet Routers generate several URL (/users/) (/users/<id>) mapping with corresponding HTTP method (CRUD Operations).
router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)

urlpatterns = [
    path("", include("core.urls")),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path("fortytwo/", include("fortytwo.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("prometheus/", include("django_prometheus.urls")),
    path("chat/", include("chat.urls")),
    path("game/", include("game.urls"))
]

42_cursus/Transcendence/T1/django/ft_transcendence/game/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'game'

urlpatterns = [
	path("play/", views.play, name='play'),
	path("tournament/", views.tournament, name='tournament'),
	path("waiting_game/<int:game_invitationID>", views.waiting_game, name='waiting_game'),
	path("invitation/<int:userID>", views.game_invitation, name='game_invitation'),
	path("accept_game/<int:game_invitationID>", views.accept_game, name="accept_game"),
	path("decline_game/<int:game_invitationID>", views.decline_game, name="decline_game"),
	path("test_game/", views.test_game, name='test_game'),
	path("selection", views.selection, name='selection'),
	path("invite", views.invite, name='invite'),
	path("add_victory/<uuid:game_uuid>/", views.add_victory, name='add_victory'),
	path("add_defeat/<uuid:game_uuid>/", views.add_defeat, name='add_defeat'),
	path("delete_game/<uuid:game_uuid>/", views.delete_game, name='delete_game')
]

42_cursus/Transcendence/T1/django/ft_transcendence/game/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid

class Game(models.Model):
	uuid = models.UUIDField(default=uuid.uuid4, editable=False)
	player_one 			= models.ForeignKey(User, null=True, db_index=True, related_name="player_one", on_delete=models.CASCADE)
	# player_two 			= models.OneToOneField(User, null=True, db_index=True, related_name="player_two", on_delete=models.CASCADE)
	# cursor_player_one	= models.IntegerField(default=0)
	# score_player_one	= models.IntegerField(default=0)
	# cursor_player_two	= models.IntegerField(default=0)
	# score_player_one	= models.IntegerField(default=0)
	# x_ball_position		= models.IntegerField(default=0)
	# y_ball_position		= models.IntegerField(default=0)
	# timer				= models.IntegerField(default=0)

class Invitation(models.Model):
	invitation_sender	= models.ForeignKey(User, null=True, db_index=True, related_name="invitation_sender", on_delete=models.CASCADE)
	invitation_receiver	= models.ForeignKey(User, null=True, db_index=True, related_name="invitation_receiver", on_delete=models.CASCADE)
	player_one_ready	= models.BooleanField(default=False)
	player_two_ready	= models.BooleanField(default=False)

42_cursus/Transcendence/T1/django/ft_transcendence/game/views.py
from django.http import HttpResponse
from django.urls import reverse
from django.shortcuts import render, redirect
from game.models import Game, Invitation
from django.urls import reverse
from core.models import Notification
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.views.decorators.cache import never_cache
from django.contrib.auth.models import User
from django.views.decorators.csrf import csrf_exempt

@login_required
def	play(request):
	try:
		game = Game.objects.create(player_one=request.user)
	except:
		return redirect(reverse('core:home'))
	context = {
		"game_uuid": game.uuid
	}

	return render(request, "game/play.html", context)

@login_required
def	tournament(request):
	return render(request, "game/tournament.html")

@login_required
def	waiting_game(request, game_invitationID):
	try :
		game_invitation = Invitation.objects.get(id=game_invitationID)
		if ( game_invitation.invitation_receiver != request.user and game_invitation.invitation_sender != request.user ):
			raise Exception(f'No Game Invitation exists for {request.user}')
	except Exception as e:
		print(e)
		request.session["message_to_user"] = f"No Game Invitation exists for {request.user}"
		return redirect('core:home')

	context = {
		"game_id": game_invitationID,
		"player_one": game_invitation.invitation_sender,
		"player_two": game_invitation.invitation_receiver,
		"player": "player_one" if request.user == game_invitation.invitation_sender else "player_two",
	}
	return render(request, "game/waiting_game.html", context)

@login_required
def	game_invitation(request, userID):
	try:
		receiver			= User.objects.get(id=userID)
		game_invitation, created	= Invitation.objects.get_or_create(
			invitation_sender=request.user,
			invitation_receiver=receiver
		)
		Notification.objects.get_or_create(
			receiver=receiver,
			game_invitation=game_invitation
		)
	except User.DoesNotExist as e:
		request.session['notification'] = "User Does Not Exists"
		return redirect(reverse('core:social'))
	except Exception as e:
		print(e)
		return render(request, "core/500.html", {"exception": e})

	request.session['notification'] = "Invitation has been sent !"
	return redirect("game:waiting_game", game_invitationID=game_invitation.id)

def	test_game(request, userID):
	return render(request, "game/test_game.html")

@login_required
def	accept_game(request, game_invitationID):
	try:
		notification	= Notification.objects.get(game_invitation=game_invitationID)
		notification.delete()
	except Exception as e:
		print(e)
		return render(request, "core/500.html", { 'exception': e })

	return redirect("game:waiting_game", game_invitationID=game_invitationID)

@login_required
def	decline_game(request, game_invitationID):
	try:
		game_invitation	= Invitation.objects.get(id=game_invitationID)
		game_invitation.delete()
	except Exception as e:
		print(e)
		return render(request, "core/500.html", { "exception": e })

	request.session['message_to_user'] = "You have declined the Game Request"
	return redirect(reverse('core:notifications'))

@login_required
def	selection(request):
	return render(request, "game/selection.html")

@login_required
def invite(request):
	friend_list = request.user.userprofile.friends.all()
	context = {
		'friend_list': friend_list,
	}
	return render(request, 'game/invite.html', context)

@login_required
@csrf_exempt
def	add_victory(request, game_uuid):
	try:
		game = Game.objects.get(uuid=game_uuid)
		request.user.userprofile.victory+=1
		request.user.userprofile.save()
	except:
		request.session['message_to_user'] = "Game Does not Exist. Impossible to add a victory point"
		return redirect(reverse('core:home'))
	return HttpResponse("Victory Point Added", status=200)

@login_required
@csrf_exempt
def	add_defeat(request, game_uuid):
	try:
		game = Game.objects.get(uuid=game_uuid)
		request.user.userprofile.defeat+=1
		request.user.userprofile.save()
	except:
		request.session['message_to_user'] = "Game Does not Exist. Impossible to add a defeat point"
		return redirect(reverse('core:home'))
	return HttpResponse("Defeat Point Added", status=200)

@login_required
@csrf_exempt
def	delete_game(request, game_uuid):
	try:
		game = Game.objects.get(uuid=game_uuid)
		game.delete()
		game.save()
	except:
		request.session['message_to_user'] = "Game Does not Exist. Impossible to delete Game Session."
		return redirect(reverse('core:home'))
	return HttpResponse("Game Deleted", status=200)
0

42_cursus/Transcendence/T1/django/ft_transcendence/game/templates/game/invitation.html
{% load socialaccount %}
{% load static %}
{% include 'core/sidenav.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
    {{ game_name|json_script:"game-name" }}
    <!---------- Background Video ---------->
    <video autoplay muted loop class="video-background">
        <source src="{% static 'core/images/planet-background.mp4' %}" type="video/mp4">
        Your browser does not support the video tag.
    </video>
</body>
</html>

42_cursus/Transcendence/T1/django/ft_transcendence/game/templates/game/invite.html
{% load socialaccount %}
{% load static %}
{% include 'core/sidenav.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'game/css/invite.css' %}">
</head>
<body>
    <!---------- Background Video ---------->
    <video autoplay muted loop class="video-background">
        <source src="{% static 'core/images/planet-background.mp4' %}" type="video/mp4">
        Your browser does not support the video tag.
    </video>

	<div class="invite-container">
		{% if friend_list %}
			<h1 class="item">Invite a friend!</h1>
			<ul class="friend-list">
				{% for friend in friend_list %}
					<li class="item">
						<span>{{ friend.username }}</span>
						<button class="buttons-design">
							<a href="{% url 'game:game_invitation' friend.id %}">
								<span>Invite</span>
							</a>
						</button>
					</li>
				{% endfor %}
			</ul>
		{% else %}
			<div class="no-friends">
				<h1 class="item">You don't have any friends yet!</h1>
				<button class="buttons-design">
					<a href="{% url 'core:social' %}">
						<span> Go to Social Tab </span>
					</a>
				</button>
			</div>
		{% endif %}
	</div>
	
</body>
</html>

42_cursus/Transcendence/T1/django/ft_transcendence/game/templates/game/play.html
{% load socialaccount %}
{% load static %}
{% include 'core/sidenav.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'game/css/play.css' %}">
    <link rel="stylesheet" href="{% static 'game/css/game.css' %}">
</head>
<body>
    <!---------- Background Video ---------->
    <video autoplay muted loop class="video-background">
        <source src="{% static 'core/images/planet-background.mp4' %}" type="video/mp4">
        Your browser does not support the video tag.
    </video>

    <div class="board">
        <div class='ball'>
            <div class="ball_effect"></div>
        </div>
            <div class="paddle_1 paddle"></div>
        <div class="paddle_2  paddle"></div>
        <div class="player_1_username"> {{ player_one }}</div>
        <div class="player_2_username"> {{ player_two }}</div>
        <h1 class="player_1_score">0</h1>
        <h1 class="player_2_score">0</h1>
        <h1 class="message">
            Press Enter to Play Pong
        </h1>
    </div>

    {{ game_uuid|json_script:"game_uuid" }}
    {{ user.username|json_script:"username" }}

    <script>
        const victoryImagePath = "{% static 'core/images/win-logo3.png' %}";
        const homeURL = "{% url 'core:home' %}";
        const playURL = "{% url 'game:play' %}";
        const tournament = false;
    </script>
    <script src="{% static 'game/js/utils.js' %}"></script>
    <script src="{% static 'game/js/play.js' %}"></script>

</body>
</html>

42_cursus/Transcendence/T1/django/ft_transcendence/game/templates/game/selection.html
{% load socialaccount %}
{% load static %}
{% include 'core/sidenav.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'game/css/selection.css' %}">
    <link rel="stylesheet" href="{% static 'game/css/tournament.css' %}">

</head>
<body>
    <!---------- Background Video ---------->
    <video autoplay muted loop class="video-background">
        <source src="{% static 'core/images/planet-background.mp4' %}" type="video/mp4">
        Your browser does not support the video tag.
    </video>


    <div class="container-selection">
        <div class="selection--options container-players">
            <div class="selection">
                <button class="selection--buttons buttons-design">
                    <a href="{% url 'game:play' %}">
                        <span> Local Game </span>
                    </a>
                </button>
                <button class="selection--buttons buttons-design">
                    <a href="{% url 'game:tournament' %}">
                        <span> Tournament </span>
                    </a>
                </button>
            </div>
        </div>
</body>
</html>

42_cursus/Transcendence/T1/django/ft_transcendence/game/templates/game/tournament.html
{% load socialaccount %}
{% load static %}
{% include 'core/sidenav.html' %}


<!DOCTYPE html>
<html lang="en">
	<head>
		<link rel="stylesheet" href="{% static 'css/main.css' %}">
		<link rel="stylesheet" href="{% static 'game/css/play.css' %}">
		<link rel="stylesheet" href="{% static 'game/css/tournament.css' %}">
		<link rel="stylesheet" href="{% static 'core/css/social.css' %}">
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">

	</head>

	<body class="no-scroll">
		<!---------- Global container for layout management ---------->
		<div class="container">
			<video autoplay muted loop class="video-background">
				<source src="{% static 'core/images/planet-background.mp4' %}" type="video/mp4">
				Your browser does not support the video tag.
			</video>

			<div class="tournament-title">
				<h1 class="social--title-style">Tournament</h1>
			</div>


			<div class="container-players">
				<div class="players-column">
					<label for="player-one"></label>
					<input type="text" id="player-one" value="{{ user.username }}" class="change-btn" disabled />
					<label for="player-two"></label>
					<input type="text" id="player-two" placeholder="Player Two" class="change-btn" required maxlength="8">
				</div>
				<div class="players-column">
					<label for="player-three"></label>
					<input type="text" id="player-three" placeholder="Player Three" class="change-btn" required maxlength="8">

					<label for="player-four"></label>
					<input type="text" id="player-four" placeholder="Player Four" class="change-btn" required maxlength="8">

					<button id="playButton" class="play-button buttons-design">Play</button>
				</div>
			</div>

			<div class="game-container hidden">
				<div id="game-area">
					<div class="player_1_username"></div>
					<div class="player_2_username"></div>
				</div>
			</div>
		</div>

	</body>

	<script>
		const gameURL = "{% url 'game:play' %}"
		const gameJS = "{% static 'game/js/play.js' %}"
        const victoryImagePath = "{% static 'core/images/win-logo3.png' %}";
		const tournament = true
        const playURL = "{% url 'game:tournament' %}";
		const homeURL = "{% url 'core:home' %}";
	</script>

	<script src="{% static 'game/js/utils.js' %}"></script>
	<script src="{% static 'game/js/tournament.js' %}"></script>

</html>

42_cursus/Transcendence/T1/django/ft_transcendence/game/templates/game/waiting_game.html
{% load socialaccount %}
{% load static %}
{% include 'core/sidenav.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'game/css/waiting_game.css' %}">
</head>
<body>
<body>
    {{ game_id|json_script:"game_id" }}

    <!---------- Background Video ---------->
    <video autoplay muted loop class="video-background">
        <source src="{% static 'core/images/planet-background.mp4' %}" type="video/mp4">
        Your browser does not support the video tag.
    </video>

    <script>
        const currentPlayer = "{{ player }}"; // This could be "player_one" or "player_two"
    </script>
    
    <!---------- Ready Section ---------->
    <div class="ready-container">   
        <div class="player" id="player-one">
            <h2 class="item">{{ player_one.username }} (P1)</h2>
            <button class="buttons-design" id="player-one-button">Ready?</button>
        </div>
        <div class="player" id="player-two">
            <h2 class="item">{{ player_two.username }} (P2)</h2>
            <button class="buttons-design" id="player-two-button">Ready?</button>
        </div>
    </div>

    <!---------- Countdown Section ---------->
    <div class="countdown" id="countdown" style="display: none;">3</div>

    <script src="{% static 'game/js/waiting_game.js' %}"></script>
</body>


    

</body>
</html>