42_cursus/Transcendence/T1/django/ft_transcendence/chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'

urlpatterns = [
    path("", views.index, name="index"),
    path("<str:room_name>/<int:userID>", views.room, name="room"),
    path("<int:userID>/", views.get_room_redirect, name="get_room_redirect"),
    path("direct_message/", views.direct_message, name='direct_message')
]

42_cursus/Transcendence/T1/django/ft_transcendence/core/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'core'

urlpatterns = [
	path("", views.login, name="login"),
	path("mfa/", views.mfa, name="mfa"),
	path("logout/", views.logout, name="logout"),
	path("home/", views.home, name="home"),
	path("my_profile/", views.my_profile, name="my_profile"),
	path("profile/<str:username>", views.profile, name="profile"),
	path("social/", views.social, name="social"),
	path("send_friend_request/<int:userID>/", views.send_friend_request, name="send_friend_request"),
	path("accept_friend_request/<int:friendRequestID>/", views.accept_friend_request, name="accept_friend_request"),
	path("decline_friend_request/<int:friendRequestID>/", views.decline_friend_request, name="decline_friend_request"),
	path("cancel_friend_request/<int:userID>/", views.cancel_friend_request, name="cancel_friend_request"),
	path("remove_friend/<int:friendID>/", views.remove_friend, name="remove_friend"),
	path("block_user/<int:userID>/", views.block_user, name="block_user"),
	path("notifications/", views.notifications, name="notifications"),
	path("unblock_user/<int:userID>/", views.unblock_user, name="unblock_user")

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

42_cursus/Transcendence/T1/django/ft_transcendence/ft_transcendence/urls.py
from django.contrib import admin
from django.urls import include, path
from core import views
from django.contrib.auth.models import User
from rest_framework import routers
from api import views
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

# Routers provide an easy way of automatically determining the URL conf.
# Because we use ViewSet Routers generate several URL (/users/) (/users/<id>) mapping with corresponding HTTP method (CRUD Operations).
router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)

urlpatterns = [
    path("", include("core.urls")),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path("fortytwo/", include("fortytwo.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("prometheus/", include("django_prometheus.urls")),
    path("chat/", include("chat.urls")),
    path("game/", include("game.urls"))
]

42_cursus/Transcendence/T1/django/ft_transcendence/templates/mfa/totp/activate_form.html
{% extends "allauth/layouts/base.html" %}
{% load allauth i18n %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
<div class="container">
	<!-- Background Video -->
	<video autoplay muted loop class="video-background">
		<source src="{% static 'core/images/planet-background.mp4' %}" type="video/mp4">
		Your browser does not support the video tag.
	</video>

	<!-- Authenticator App Activation Section -->
	<div class="auth-app">
		<header class="auth-header">
			<h1 class="auth-title">
				{% translate "Activate Authenticator App" %}
			</h1>
			<p class="auth-description">
				{% blocktranslate %}
				To protect your account with two-factor authentication, scan the QR code below with your authenticator app. Then, input the verification code generated by the app below.
				{% endblocktranslate %}
			</p>
		</header>

		<section class="auth-content">
			{% url 'mfa_activate_totp' as action_url %}
			<form method="post" action="{{ action_url }}" class="auth-form">
				{% csrf_token %}
				{{ form.code.errors }}
				<!-- QR Code Section -->
				<div class="qr-code-container">
					<img src="{{ totp_svg_data_uri }}" alt="{% trans 'QR code for authentication' %}" class="qr-code">
				</div>

				<!-- Authenticator Secret -->
				<div class="form-group">
					<label for="authenticator_secret" class="form-label">{% translate "Authenticator secret" %}</label>
					<input
						id="authenticator_secret"
						type="text"
						value="{{ form.secret }}"
						disabled
						class="form-control"
						name="authentication"
					>
					<small class="form-help-text">
						{% translate "You can store this secret and use it to reinstall your authenticator app at a later time." %}
					</small>
				</div>
				<div class="form-group">
                    {% render_field form.code placeholder="Code" id="password" class="form-control" %}


				<!-- Form Actions -->
				<div class="form-actions">
					<input type="hidden" name="next" value="{% url 'core:my_profile' %}">
					<button type="submit" class="btn btn-primary">Activate</button>
				</div>
			</form>
		</section>
	</div>
</div>
{% endblock content %}

42_cursus/Transcendence/T1/django/ft_transcendence/templates/mfa/totp/deactivate_form.html
{% extends "allauth/layouts/base.html" %}
{% load i18n %}
{% load allauth %}
{% load widget_tweaks %}
{% load static %}

{% block head_title %}
    {% trans "Deactivate Authenticator App" %}
{% endblock head_title %}

{% block content %}
<video autoplay muted loop class="video-background">
		<source src="{% static 'core/images/planet-background.mp4' %}" type="video/mp4">
		Your browser does not support the video tag.
</video>

    {% url 'mfa_deactivate_totp' as action_url %}

	<div class="container">
		<div class="auth-app">
			<header class="auth-header">
				<h1 class="auth-title">
					{% translate "Deactivate Authenticator App" %}
				</h1>
				<p class="auth-description">
					{% blocktranslate %}
					You are about to deactivate authenticator app based authentication. Are you sure ?
					{% endblocktranslate %}
				</p>
			</header>

			<form method="POST" action="{% url 'mfa_deactivate_totp' %}" id="mfa_deactivate_totp" class="mfa-form">
				{% csrf_token %}

				<div class="container--submit-button gap">

					<input type="hidden" name="next" value="{% url 'mfa_activate_totp' %}">
					<button type="button" onclick="window.history.back();" class="btn btn-primary">
						{% trans "Back" %}
					</button>
					<button type="submit" class="btn btn-primary">Deactivate 2FA</button>
				</div>
			</form>
		</div>
	</div>

{% endblock content %}